### ISSUE TITLE
Cannot generate an app

### ISSUE THREAD

**Issue by ahelmel** [Hotell/ng-cli-schematics#34]
Hi,

I just installed the schematics. After running the command:
`ng new my-app --collection=@martin_hotell/schematics` 

i get the error:
`Schematic "ng-new" not found in collection "@martin_hotell/schematics".
Error: Schematic "ng-new" not found in collection "@martin_hotell/schematics".
    at SchematicEngine.createSchematic (/Users/arthurhelmel/.nvm/versions/node/v8.9.4/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:155:23)
    at CollectionImpl.createSchematic (/Users/arthurhelmel/.nvm/versions/node/v8.9.4/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/collection.js:12:29)
    at Object.getSchematic (/Users/arthurhelmel/.nvm/versions/node/v8.9.4/lib/node_modules/@angular/cli/utilities/schematics.js:36:23)
    at NewCommand.getOptions (/Users/arthurhelmel/.nvm/versions/node/v8.9.4/lib/node_modules/@angular/cli/models/schematic-command.js:194:40)
    at NewCommand.initialize (/Users/arthurhelmel/.nvm/versions/node/v8.9.4/lib/node_modules/@angular/cli/commands/new.js:48:21)
    at Object.<anonymous> (/Users/arthurhelmel/.nvm/versions/node/v8.9.4/lib/node_modules/@angular/cli/models/command-runner.js:87:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/arthurhelmel/.nvm/versions/node/v8.9.4/lib/node_modules/@angular/cli/models/command-runner.js:4:58)
    at <anonymous>`.

I am using `Angular CLI: 6.0.3`, `Node: 8.9.4` and `@schematics/angular 0.6.3` on `OS: darwin x64` `(macOS High Sierra, 10.13.4).`

**Comment by Hotell** [comment]
This schematic is for ng cli 1.* 
It needs to be rewritten to apply all the breaking changes for cli 6. I'll update docs to make it obvious. Cheers
